### ISSUE TITLE
Error on windows on no-webpack brach, just cloned "npm i" and "npm run start"

### ISSUE THREAD

**Issue by emersonbottero** [thepassle/create-lit-app#4]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle create-lit-app@~prestart: create-lit-app@
6 info lifecycle create-lit-app@~start: create-lit-app@
7 verbose lifecycle create-lit-app@~start: unsafe-perm in lifecycle true
8 verbose lifecycle create-lit-app@~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;T:\Clientes\EBB\create-lit-app\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;T:\Program Files (x86)\Apache\maven\bin;C:\Program Files\PuTTY\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Pandoc\;C:\Users\emers\AppData\Local\Microsoft\WindowsApps;C:\Users\emers\AppData\Local\GitHubDesktop\bin;C:\Users\emers\AppData\Roaming\npm;T:\Program Files\Microsoft VS Code\bin
9 verbose lifecycle create-lit-app@~start: CWD: T:\Clientes\EBB\create-lit-app
10 silly lifecycle create-lit-app@~start: Args: [ '/d /s /c',
10 silly lifecycle   'nodemon server.js | npm run watch | polymer serve --proxy-path /api/books --proxy-target http://localhost:8000/api/books' ]
11 silly lifecycle create-lit-app@~start: Returned: code: 255  signal: null
12 info lifecycle create-lit-app@~start: Failed to exec start script
13 verbose stack Error: create-lit-app@ start: `nodemon server.js | npm run watch | polymer serve --proxy-path /api/books --proxy-target http://localhost:8000/api/books`
13 verbose stack Exit status 255
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid create-lit-app@
15 verbose cwd T:\Clientes\EBB\create-lit-app
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 255
22 error create-lit-app@ start: `nodemon server.js | npm run watch | polymer serve --proxy-path /api/books --proxy-target http://localhost:8000/api/books`
22 error Exit status 255
23 error Failed at the create-lit-app@ start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 255, true ]

**Comment by thepassle** [comment]
Will look into it. It might be a problem with nodemon, I see that its not in the package.json as a dependency. Can you try installing nodemon and running `npm start` again, or changing the `start` script to:
`   "start": "node server.js | npm run watch | polymer serve --proxy-path /api/books --proxy-target http://localhost:8000/api/books",`

**Comment by emersonbottero** [comment]
installing nodemon worked
