### ISSUE TITLE
Add in an js lib to my app - firebase.js

### ISSUE THREAD

**Issue by davie-robertson** [thepassle/create-lit-app#7]
Sorry if this is obvious, but I'm don't seem to be able to add firebase.js to an app I created with create-lib-app.

I've placed a <script> tag to load the file from index.html (which is how I've usually added it to a lit-element app in the past) - but the app isn't seeing it from any of my elements/.js pages

**Comment by thepassle** [comment]
You should be able to import firebase as a module in your components

From the docs:

> If you are using ES6 imports or TypeScript:
> 
> `import firebase from 'firebase';`
> `var app = firebase.initializeApp({ ... });`

Alternatively, this might be of help:
https://github.com/Polymer/pwa-starter-kit/issues/196#issuecomment-407220616

Please let me know if it helped :)

**Comment by davie-robertson** [comment]
I'll give that try, I know that it wasn't working in another project we're working on as they have not got a working ES6 import:
https://github.com/firebase/firebase-js-sdk/issues/834
maybe they fixed it - but I seem to recall that was a false start last time I tried..
https://github.com/firebase/firebase-js-sdk/issues/815

I know this isn't related to your project - but an FAQ entry on how you add a lib to your code would really help - there's nothing explaining the vendor folder and the 'redirects/mapping' code for us beginners.

thanks

D.

**Comment by thepassle** [comment]
Thanks for the feedback :) I'll see if i can get it working locally tomorrow, and keep you updated in this issue. I agree that it would be a great addition to the faq.

Im currently working on making create-lit-app a bit more accessible for beginners, its not really battle tested yet, but you can take a sneak peak over here: https://github.com/thepassle/create-lit-app-advanced and https://github.com/thepassle/create-lit-app-mini

This repo will be updated shortly as well. The vendor folder as of now contains a regenerator runtime file, which is needed to polyfill async/await. In the new build I'm using @babel/plugin-transform-runtime to do that instead.
