### ISSUE TITLE
create-lit-app-advanced repo link points to wrong location

### ISSUE THREAD

**Issue by j-wil** [thepassle/create-lit-app#9]
README.md has 3 locations where a link implies it points to another repo but takes you to stackblitzs instead.

[redux section](https://github.com/thepassle/create-lit-app#redux)
[routing section](https://github.com/thepassle/create-lit-app#routing)
[adding-an-api section](https://github.com/thepassle/create-lit-app#adding-an-api)

Expected results:
create-lit-app-advanced repo link takes you to https://github.com/thepassle/create-lit-app-advanced instead of https://stackblitz.com/edit/create-lit-app

**Comment by thepassle** [comment]
Good find, thanks! Will fix tonight :)
